#!/bin/sh

modprobe i2c-bcm2708
modprobe i2c-dev
modprobe spi-bcm2835
modprobe industrialio-sw-trigger
modprobe iio-trig-hrtimer
modprobe iio-trig-loop
modprobe ak8975
modprobe ms5611_i2c
modprobe st_pressure_i2c
modprobe inv-mpu6050-i2c
modprobe inv-mpu6050-spi
modprobe zpa2326-i2c
modprobe zpa2326-spi
